server:
  port: 9082

spring:
  application:
    name: ms-reserva
  config:
    import: optional:configserver:http://localhost:9888
  datasource:
    url: jdbc:h2:mem:reserva
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9081/.well-known/jwks.json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka/
  instance:
    prefer-ip-address: true

---
spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5442/reserva_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
